<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kota =  array(
            0 => array('id' => '1101', 'provinsi_id' => '11', 'kota' => 'KABUPATEN SIMEULUE'),
            1 => array('id' => '1102', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH SINGKIL'),
            2 => array('id' => '1103', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH SELATAN'),
            3 => array('id' => '1104', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH TENGGARA'),
            4 => array('id' => '1105', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH TIMUR'),
            5 => array('id' => '1106', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH TENGAH'),
            6 => array('id' => '1107', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH BARAT'),
            7 => array('id' => '1108', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH BESAR'),
            8 => array('id' => '1109', 'provinsi_id' => '11', 'kota' => 'KABUPATEN PIDIE'),
            9 => array('id' => '1110', 'provinsi_id' => '11', 'kota' => 'KABUPATEN BIREUEN'),
            10 => array('id' => '1111', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH UTARA'),
            11 => array('id' => '1112', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH BARAT DAYA'),
            12 => array('id' => '1113', 'provinsi_id' => '11', 'kota' => 'KABUPATEN GAYO LUES'),
            13 => array('id' => '1114', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH TAMIANG'),
            14 => array('id' => '1115', 'provinsi_id' => '11', 'kota' => 'KABUPATEN NAGAN RAYA'),
            15 => array('id' => '1116', 'provinsi_id' => '11', 'kota' => 'KABUPATEN ACEH JAYA'),
            16 => array('id' => '1117', 'provinsi_id' => '11', 'kota' => 'KABUPATEN BENER MERIAH'),
            17 => array('id' => '1118', 'provinsi_id' => '11', 'kota' => 'KABUPATEN PIDIE JAYA'),
            18 => array('id' => '1171', 'provinsi_id' => '11', 'kota' => 'KOTA BANDA ACEH'),
            19 => array('id' => '1172', 'provinsi_id' => '11', 'kota' => 'KOTA SABANG'),
            20 => array('id' => '1173', 'provinsi_id' => '11', 'kota' => 'KOTA LANGSA'),
            21 => array('id' => '1174', 'provinsi_id' => '11', 'kota' => 'KOTA LHOKSEUMAWE'),
            22 => array('id' => '1175', 'provinsi_id' => '11', 'kota' => 'KOTA SUBULUSSALAM'),
            23 => array('id' => '1201', 'provinsi_id' => '12', 'kota' => 'KABUPATEN NIAS'),
            24 => array('id' => '1202', 'provinsi_id' => '12', 'kota' => 'KABUPATEN MANDAILING NATAL'),
            25 => array('id' => '1203', 'provinsi_id' => '12', 'kota' => 'KABUPATEN TAPANULI SELATAN'),
            26 => array('id' => '1204', 'provinsi_id' => '12', 'kota' => 'KABUPATEN TAPANULI TENGAH'),
            27 => array('id' => '1205', 'provinsi_id' => '12', 'kota' => 'KABUPATEN TAPANULI UTARA'),
            28 => array('id' => '1206', 'provinsi_id' => '12', 'kota' => 'KABUPATEN TOBA SAMOSIR'),
            29 => array('id' => '1207', 'provinsi_id' => '12', 'kota' => 'KABUPATEN LABUHAN BATU'),
            30 => array('id' => '1208', 'provinsi_id' => '12', 'kota' => 'KABUPATEN ASAHAN'),
            31 => array('id' => '1209', 'provinsi_id' => '12', 'kota' => 'KABUPATEN SIMALUNGUN'),
            32 => array('id' => '1210', 'provinsi_id' => '12', 'kota' => 'KABUPATEN DAIRI'),
            33 => array('id' => '1211', 'provinsi_id' => '12', 'kota' => 'KABUPATEN KARO'),
            34 => array('id' => '1212', 'provinsi_id' => '12', 'kota' => 'KABUPATEN DELI SERDANG'),
            35 => array('id' => '1213', 'provinsi_id' => '12', 'kota' => 'KABUPATEN LANGKAT'),
            36 => array('id' => '1214', 'provinsi_id' => '12', 'kota' => 'KABUPATEN NIAS SELATAN'),
            37 => array('id' => '1215', 'provinsi_id' => '12', 'kota' => 'KABUPATEN HUMBANG HASUNDUTAN'),
            38 => array('id' => '1216', 'provinsi_id' => '12', 'kota' => 'KABUPATEN PAKPAK BHARAT'),
            39 => array('id' => '1217', 'provinsi_id' => '12', 'kota' => 'KABUPATEN SAMOSIR'),
            40 => array('id' => '1218', 'provinsi_id' => '12', 'kota' => 'KABUPATEN SERDANG BEDAGAI'),
            41 => array('id' => '1219', 'provinsi_id' => '12', 'kota' => 'KABUPATEN BATU BARA'),
            42 => array('id' => '1220', 'provinsi_id' => '12', 'kota' => 'KABUPATEN PADANG LAWAS UTARA'),
            43 => array('id' => '1221', 'provinsi_id' => '12', 'kota' => 'KABUPATEN PADANG LAWAS'),
            44 => array('id' => '1222', 'provinsi_id' => '12', 'kota' => 'KABUPATEN LABUHAN BATU SELATAN'),
            45 => array('id' => '1223', 'provinsi_id' => '12', 'kota' => 'KABUPATEN LABUHAN BATU UTARA'),
            46 => array('id' => '1224', 'provinsi_id' => '12', 'kota' => 'KABUPATEN NIAS UTARA'),
            47 => array('id' => '1225', 'provinsi_id' => '12', 'kota' => 'KABUPATEN NIAS BARAT'),
            48 => array('id' => '1271', 'provinsi_id' => '12', 'kota' => 'KOTA SIBOLGA'),
            49 => array('id' => '1272', 'provinsi_id' => '12', 'kota' => 'KOTA TANJUNG BALAI'),
            50 => array('id' => '1273', 'provinsi_id' => '12', 'kota' => 'KOTA PEMATANG SIANTAR'),
            51 => array('id' => '1274', 'provinsi_id' => '12', 'kota' => 'KOTA TEBING TINGGI'),
            52 => array('id' => '1275', 'provinsi_id' => '12', 'kota' => 'KOTA MEDAN'),
            53 => array('id' => '1276', 'provinsi_id' => '12', 'kota' => 'KOTA BINJAI'),
            54 => array('id' => '1277', 'provinsi_id' => '12', 'kota' => 'KOTA PADANGSIDIMPUAN'),
            55 => array('id' => '1278', 'provinsi_id' => '12', 'kota' => 'KOTA GUNUNGSITOLI'),
            56 => array('id' => '1301', 'provinsi_id' => '13', 'kota' => 'KABUPATEN KEPULAUAN MENTAWAI'),
            57 => array('id' => '1302', 'provinsi_id' => '13', 'kota' => 'KABUPATEN PESISIR SELATAN'),
            58 => array('id' => '1303', 'provinsi_id' => '13', 'kota' => 'KABUPATEN SOLOK'),
            59 => array('id' => '1304', 'provinsi_id' => '13', 'kota' => 'KABUPATEN SIJUNJUNG'),
            60 => array('id' => '1305', 'provinsi_id' => '13', 'kota' => 'KABUPATEN TANAH DATAR'),
            61 => array('id' => '1306', 'provinsi_id' => '13', 'kota' => 'KABUPATEN PADANG PARIAMAN'),
            62 => array('id' => '1307', 'provinsi_id' => '13', 'kota' => 'KABUPATEN AGAM'),
            63 => array('id' => '1308', 'provinsi_id' => '13', 'kota' => 'KABUPATEN LIMA PULUH KOTA'),
            64 => array('id' => '1309', 'provinsi_id' => '13', 'kota' => 'KABUPATEN PASAMAN'),
            65 => array('id' => '1310', 'provinsi_id' => '13', 'kota' => 'KABUPATEN SOLOK SELATAN'),
            66 => array('id' => '1311', 'provinsi_id' => '13', 'kota' => 'KABUPATEN DHARMASRAYA'),
            67 => array('id' => '1312', 'provinsi_id' => '13', 'kota' => 'KABUPATEN PASAMAN BARAT'),
            68 => array('id' => '1371', 'provinsi_id' => '13', 'kota' => 'KOTA PADANG'),
            69 => array('id' => '1372', 'provinsi_id' => '13', 'kota' => 'KOTA SOLOK'),
            70 => array('id' => '1373', 'provinsi_id' => '13', 'kota' => 'KOTA SAWAH LUNTO'),
            71 => array('id' => '1374', 'provinsi_id' => '13', 'kota' => 'KOTA PADANG PANJANG'),
            72 => array('id' => '1375', 'provinsi_id' => '13', 'kota' => 'KOTA BUKITTINGGI'),
            73 => array('id' => '1376', 'provinsi_id' => '13', 'kota' => 'KOTA PAYAKUMBUH'),
            74 => array('id' => '1377', 'provinsi_id' => '13', 'kota' => 'KOTA PARIAMAN'),
            75 => array('id' => '1401', 'provinsi_id' => '14', 'kota' => 'KABUPATEN KUANTAN SINGINGI'),
            76 => array('id' => '1402', 'provinsi_id' => '14', 'kota' => 'KABUPATEN INDRAGIRI HULU'),
            77 => array('id' => '1403', 'provinsi_id' => '14', 'kota' => 'KABUPATEN INDRAGIRI HILIR'),
            78 => array('id' => '1404', 'provinsi_id' => '14', 'kota' => 'KABUPATEN PELALAWAN'),
            79 => array('id' => '1405', 'provinsi_id' => '14', 'kota' => 'KABUPATEN S I A K'),
            80 => array('id' => '1406', 'provinsi_id' => '14', 'kota' => 'KABUPATEN KAMPAR'),
            81 => array('id' => '1407', 'provinsi_id' => '14', 'kota' => 'KABUPATEN ROKAN HULU'),
            82 => array('id' => '1408', 'provinsi_id' => '14', 'kota' => 'KABUPATEN BENGKALIS'),
            83 => array('id' => '1409', 'provinsi_id' => '14', 'kota' => 'KABUPATEN ROKAN HILIR'),
            84 => array('id' => '1410', 'provinsi_id' => '14', 'kota' => 'KABUPATEN KEPULAUAN MERANTI'),
            85 => array('id' => '1471', 'provinsi_id' => '14', 'kota' => 'KOTA PEKANBARU'),
            86 => array('id' => '1473', 'provinsi_id' => '14', 'kota' => 'KOTA D U M A I'),
            87 => array('id' => '1501', 'provinsi_id' => '15', 'kota' => 'KABUPATEN KERINCI'),
            88 => array('id' => '1502', 'provinsi_id' => '15', 'kota' => 'KABUPATEN MERANGIN'),
            89 => array('id' => '1503', 'provinsi_id' => '15', 'kota' => 'KABUPATEN SAROLANGUN'),
            90 => array('id' => '1504', 'provinsi_id' => '15', 'kota' => 'KABUPATEN BATANG HARI'),
            91 => array('id' => '1505', 'provinsi_id' => '15', 'kota' => 'KABUPATEN MUARO JAMBI'),
            92 => array('id' => '1506', 'provinsi_id' => '15', 'kota' => 'KABUPATEN TANJUNG JABUNG TIMUR'),
            93 => array('id' => '1507', 'provinsi_id' => '15', 'kota' => 'KABUPATEN TANJUNG JABUNG BARAT'),
            94 => array('id' => '1508', 'provinsi_id' => '15', 'kota' => 'KABUPATEN TEBO'),
            95 => array('id' => '1509', 'provinsi_id' => '15', 'kota' => 'KABUPATEN BUNGO'),
            96 => array('id' => '1571', 'provinsi_id' => '15', 'kota' => 'KOTA JAMBI'),
            97 => array('id' => '1572', 'provinsi_id' => '15', 'kota' => 'KOTA SUNGAI PENUH'),
            98 => array('id' => '1601', 'provinsi_id' => '16', 'kota' => 'KABUPATEN OGAN KOMERING ULU'),
            99 => array('id' => '1602', 'provinsi_id' => '16', 'kota' => 'KABUPATEN OGAN KOMERING ILIR'),
            100 => array('id' => '1603', 'provinsi_id' => '16', 'kota' => 'KABUPATEN MUARA ENIM'),
            101 => array('id' => '1604', 'provinsi_id' => '16', 'kota' => 'KABUPATEN LAHAT'),
            102 => array('id' => '1605', 'provinsi_id' => '16', 'kota' => 'KABUPATEN MUSI RAWAS'),
            103 => array('id' => '1606', 'provinsi_id' => '16', 'kota' => 'KABUPATEN MUSI BANYUASIN'),
            104 => array('id' => '1607', 'provinsi_id' => '16', 'kota' => 'KABUPATEN BANYU ASIN'),
            105 => array('id' => '1608', 'provinsi_id' => '16', 'kota' => 'KABUPATEN OGAN KOMERING ULU SELATAN'),
            106 => array('id' => '1609', 'provinsi_id' => '16', 'kota' => 'KABUPATEN OGAN KOMERING ULU TIMUR'),
            107 => array('id' => '1610', 'provinsi_id' => '16', 'kota' => 'KABUPATEN OGAN ILIR'),
            108 => array('id' => '1611', 'provinsi_id' => '16', 'kota' => 'KABUPATEN EMPAT LAWANG'),
            109 => array('id' => '1612', 'provinsi_id' => '16', 'kota' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'),
            110 => array('id' => '1613', 'provinsi_id' => '16', 'kota' => 'KABUPATEN MUSI RAWAS UTARA'),
            111 => array('id' => '1671', 'provinsi_id' => '16', 'kota' => 'KOTA PALEMBANG'),
            112 => array('id' => '1672', 'provinsi_id' => '16', 'kota' => 'KOTA PRABUMULIH'),
            113 => array('id' => '1673', 'provinsi_id' => '16', 'kota' => 'KOTA PAGAR ALAM'),
            114 => array('id' => '1674', 'provinsi_id' => '16', 'kota' => 'KOTA LUBUKLINGGAU'),
            115 => array('id' => '1701', 'provinsi_id' => '17', 'kota' => 'KABUPATEN BENGKULU SELATAN'),
            116 => array('id' => '1702', 'provinsi_id' => '17', 'kota' => 'KABUPATEN REJANG LEBONG'),
            117 => array('id' => '1703', 'provinsi_id' => '17', 'kota' => 'KABUPATEN BENGKULU UTARA'),
            118 => array('id' => '1704', 'provinsi_id' => '17', 'kota' => 'KABUPATEN KAUR'),
            119 => array('id' => '1705', 'provinsi_id' => '17', 'kota' => 'KABUPATEN SELUMA'),
            120 => array('id' => '1706', 'provinsi_id' => '17', 'kota' => 'KABUPATEN MUKOMUKO'),
            121 => array('id' => '1707', 'provinsi_id' => '17', 'kota' => 'KABUPATEN LEBONG'),
            122 => array('id' => '1708', 'provinsi_id' => '17', 'kota' => 'KABUPATEN KEPAHIANG'),
            123 => array('id' => '1709', 'provinsi_id' => '17', 'kota' => 'KABUPATEN BENGKULU TENGAH'),
            124 => array('id' => '1771', 'provinsi_id' => '17', 'kota' => 'KOTA BENGKULU'),
            125 => array('id' => '1801', 'provinsi_id' => '18', 'kota' => 'KABUPATEN LAMPUNG BARAT'),
            126 => array('id' => '1802', 'provinsi_id' => '18', 'kota' => 'KABUPATEN TANGGAMUS'),
            127 => array('id' => '1803', 'provinsi_id' => '18', 'kota' => 'KABUPATEN LAMPUNG SELATAN'),
            128 => array('id' => '1804', 'provinsi_id' => '18', 'kota' => 'KABUPATEN LAMPUNG TIMUR'),
            129 => array('id' => '1805', 'provinsi_id' => '18', 'kota' => 'KABUPATEN LAMPUNG TENGAH'),
            130 => array('id' => '1806', 'provinsi_id' => '18', 'kota' => 'KABUPATEN LAMPUNG UTARA'),
            131 => array('id' => '1807', 'provinsi_id' => '18', 'kota' => 'KABUPATEN WAY KANAN'),
            132 => array('id' => '1808', 'provinsi_id' => '18', 'kota' => 'KABUPATEN TULANGBAWANG'),
            133 => array('id' => '1809', 'provinsi_id' => '18', 'kota' => 'KABUPATEN PESAWARAN'),
            134 => array('id' => '1810', 'provinsi_id' => '18', 'kota' => 'KABUPATEN PRINGSEWU'),
            135 => array('id' => '1811', 'provinsi_id' => '18', 'kota' => 'KABUPATEN MESUJI'),
            136 => array('id' => '1812', 'provinsi_id' => '18', 'kota' => 'KABUPATEN TULANG BAWANG BARAT'),
            137 => array('id' => '1813', 'provinsi_id' => '18', 'kota' => 'KABUPATEN PESISIR BARAT'),
            138 => array('id' => '1871', 'provinsi_id' => '18', 'kota' => 'KOTA BANDAR LAMPUNG'),
            139 => array('id' => '1872', 'provinsi_id' => '18', 'kota' => 'KOTA METRO'),
            140 => array('id' => '1901', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BANGKA'),
            141 => array('id' => '1902', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BELITUNG'),
            142 => array('id' => '1903', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BANGKA BARAT'),
            143 => array('id' => '1904', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BANGKA TENGAH'),
            144 => array('id' => '1905', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BANGKA SELATAN'),
            145 => array('id' => '1906', 'provinsi_id' => '19', 'kota' => 'KABUPATEN BELITUNG TIMUR'),
            146 => array('id' => '1971', 'provinsi_id' => '19', 'kota' => 'KOTA PANGKAL PINANG'),
            147 => array('id' => '2101', 'provinsi_id' => '21', 'kota' => 'KABUPATEN KARIMUN'),
            148 => array('id' => '2102', 'provinsi_id' => '21', 'kota' => 'KABUPATEN BINTAN'),
            149 => array('id' => '2103', 'provinsi_id' => '21', 'kota' => 'KABUPATEN NATUNA'),
            150 => array('id' => '2104', 'provinsi_id' => '21', 'kota' => 'KABUPATEN LINGGA'),
            151 => array('id' => '2105', 'provinsi_id' => '21', 'kota' => 'KABUPATEN KEPULAUAN ANAMBAS'),
            152 => array('id' => '2171', 'provinsi_id' => '21', 'kota' => 'KOTA B A T A M'),
            153 => array('id' => '2172', 'provinsi_id' => '21', 'kota' => 'KOTA TANJUNG PINANG'),
            154 => array('id' => '3101', 'provinsi_id' => '31', 'kota' => 'KABUPATEN KEPULAUAN SERIBU'),
            155 => array('id' => '3171', 'provinsi_id' => '31', 'kota' => 'KOTA JAKARTA SELATAN'),
            156 => array('id' => '3172', 'provinsi_id' => '31', 'kota' => 'KOTA JAKARTA TIMUR'),
            157 => array('id' => '3173', 'provinsi_id' => '31', 'kota' => 'KOTA JAKARTA PUSAT'),
            158 => array('id' => '3174', 'provinsi_id' => '31', 'kota' => 'KOTA JAKARTA BARAT'),
            159 => array('id' => '3175', 'provinsi_id' => '31', 'kota' => 'KOTA JAKARTA UTARA'),
            160 => array('id' => '3201', 'provinsi_id' => '32', 'kota' => 'KABUPATEN BOGOR'),
            161 => array('id' => '3202', 'provinsi_id' => '32', 'kota' => 'KABUPATEN SUKABUMI'),
            162 => array('id' => '3203', 'provinsi_id' => '32', 'kota' => 'KABUPATEN CIANJUR'),
            163 => array('id' => '3204', 'provinsi_id' => '32', 'kota' => 'KABUPATEN BANDUNG'),
            164 => array('id' => '3205', 'provinsi_id' => '32', 'kota' => 'KABUPATEN GARUT'),
            165 => array('id' => '3206', 'provinsi_id' => '32', 'kota' => 'KABUPATEN TASIKMALAYA'),
            166 => array('id' => '3207', 'provinsi_id' => '32', 'kota' => 'KABUPATEN CIAMIS'),
            167 => array('id' => '3208', 'provinsi_id' => '32', 'kota' => 'KABUPATEN KUNINGAN'),
            168 => array('id' => '3209', 'provinsi_id' => '32', 'kota' => 'KABUPATEN CIREBON'),
            169 => array('id' => '3210', 'provinsi_id' => '32', 'kota' => 'KABUPATEN MAJALENGKA'),
            170 => array('id' => '3211', 'provinsi_id' => '32', 'kota' => 'KABUPATEN SUMEDANG'),
            171 => array('id' => '3212', 'provinsi_id' => '32', 'kota' => 'KABUPATEN INDRAMAYU'),
            172 => array('id' => '3213', 'provinsi_id' => '32', 'kota' => 'KABUPATEN SUBANG'),
            173 => array('id' => '3214', 'provinsi_id' => '32', 'kota' => 'KABUPATEN PURWAKARTA'),
            174 => array('id' => '3215', 'provinsi_id' => '32', 'kota' => 'KABUPATEN KARAWANG'),
            175 => array('id' => '3216', 'provinsi_id' => '32', 'kota' => 'KABUPATEN BEKASI'),
            176 => array('id' => '3217', 'provinsi_id' => '32', 'kota' => 'KABUPATEN BANDUNG BARAT'),
            177 => array('id' => '3218', 'provinsi_id' => '32', 'kota' => 'KABUPATEN PANGANDARAN'),
            178 => array('id' => '3271', 'provinsi_id' => '32', 'kota' => 'KOTA BOGOR'),
            179 => array('id' => '3272', 'provinsi_id' => '32', 'kota' => 'KOTA SUKABUMI'),
            180 => array('id' => '3273', 'provinsi_id' => '32', 'kota' => 'KOTA BANDUNG'),
            181 => array('id' => '3274', 'provinsi_id' => '32', 'kota' => 'KOTA CIREBON'),
            182 => array('id' => '3275', 'provinsi_id' => '32', 'kota' => 'KOTA BEKASI'),
            183 => array('id' => '3276', 'provinsi_id' => '32', 'kota' => 'KOTA DEPOK'),
            184 => array('id' => '3277', 'provinsi_id' => '32', 'kota' => 'KOTA CIMAHI'),
            185 => array('id' => '3278', 'provinsi_id' => '32', 'kota' => 'KOTA TASIKMALAYA'),
            186 => array('id' => '3279', 'provinsi_id' => '32', 'kota' => 'KOTA BANJAR'),
            187 => array('id' => '3301', 'provinsi_id' => '33', 'kota' => 'KABUPATEN CILACAP'),
            188 => array('id' => '3302', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BANYUMAS'),
            189 => array('id' => '3303', 'provinsi_id' => '33', 'kota' => 'KABUPATEN PURBALINGGA'),
            190 => array('id' => '3304', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BANJARNEGARA'),
            191 => array('id' => '3305', 'provinsi_id' => '33', 'kota' => 'KABUPATEN KEBUMEN'),
            192 => array('id' => '3306', 'provinsi_id' => '33', 'kota' => 'KABUPATEN PURWOREJO'),
            193 => array('id' => '3307', 'provinsi_id' => '33', 'kota' => 'KABUPATEN WONOSOBO'),
            194 => array('id' => '3308', 'provinsi_id' => '33', 'kota' => 'KABUPATEN MAGELANG'),
            195 => array('id' => '3309', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BOYOLALI'),
            196 => array('id' => '3310', 'provinsi_id' => '33', 'kota' => 'KABUPATEN KLATEN'),
            197 => array('id' => '3311', 'provinsi_id' => '33', 'kota' => 'KABUPATEN SUKOHARJO'),
            198 => array('id' => '3312', 'provinsi_id' => '33', 'kota' => 'KABUPATEN WONOGIRI'),
            199 => array('id' => '3313', 'provinsi_id' => '33', 'kota' => 'KABUPATEN KARANGANYAR'),
            200 => array('id' => '3314', 'provinsi_id' => '33', 'kota' => 'KABUPATEN SRAGEN'),
            201 => array('id' => '3315', 'provinsi_id' => '33', 'kota' => 'KABUPATEN GROBOGAN'),
            202 => array('id' => '3316', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BLORA'),
            203 => array('id' => '3317', 'provinsi_id' => '33', 'kota' => 'KABUPATEN REMBANG'),
            204 => array('id' => '3318', 'provinsi_id' => '33', 'kota' => 'KABUPATEN PATI'),
            205 => array('id' => '3319', 'provinsi_id' => '33', 'kota' => 'KABUPATEN KUDUS'),
            206 => array('id' => '3320', 'provinsi_id' => '33', 'kota' => 'KABUPATEN JEPARA'),
            207 => array('id' => '3321', 'provinsi_id' => '33', 'kota' => 'KABUPATEN DEMAK'),
            208 => array('id' => '3322', 'provinsi_id' => '33', 'kota' => 'KABUPATEN SEMARANG'),
            209 => array('id' => '3323', 'provinsi_id' => '33', 'kota' => 'KABUPATEN TEMANGGUNG'),
            210 => array('id' => '3324', 'provinsi_id' => '33', 'kota' => 'KABUPATEN KENDAL'),
            211 => array('id' => '3325', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BATANG'),
            212 => array('id' => '3326', 'provinsi_id' => '33', 'kota' => 'KABUPATEN PEKALONGAN'),
            213 => array('id' => '3327', 'provinsi_id' => '33', 'kota' => 'KABUPATEN PEMALANG'),
            214 => array('id' => '3328', 'provinsi_id' => '33', 'kota' => 'KABUPATEN TEGAL'),
            215 => array('id' => '3329', 'provinsi_id' => '33', 'kota' => 'KABUPATEN BREBES'),
            216 => array('id' => '3371', 'provinsi_id' => '33', 'kota' => 'KOTA MAGELANG'),
            217 => array('id' => '3372', 'provinsi_id' => '33', 'kota' => 'KOTA SURAKARTA'),
            218 => array('id' => '3373', 'provinsi_id' => '33', 'kota' => 'KOTA SALATIGA'),
            219 => array('id' => '3374', 'provinsi_id' => '33', 'kota' => 'KOTA SEMARANG'),
            220 => array('id' => '3375', 'provinsi_id' => '33', 'kota' => 'KOTA PEKALONGAN'),
            221 => array('id' => '3376', 'provinsi_id' => '33', 'kota' => 'KOTA TEGAL'),
            222 => array('id' => '3401', 'provinsi_id' => '34', 'kota' => 'KABUPATEN KULON PROGO'),
            223 => array('id' => '3402', 'provinsi_id' => '34', 'kota' => 'KABUPATEN BANTUL'),
            224 => array('id' => '3403', 'provinsi_id' => '34', 'kota' => 'KABUPATEN GUNUNG KIDUL'),
            225 => array('id' => '3404', 'provinsi_id' => '34', 'kota' => 'KABUPATEN SLEMAN'),
            226 => array('id' => '3471', 'provinsi_id' => '34', 'kota' => 'KOTA YOGYAKARTA'),
            227 => array('id' => '3501', 'provinsi_id' => '35', 'kota' => 'KABUPATEN PACITAN'),
            228 => array('id' => '3502', 'provinsi_id' => '35', 'kota' => 'KABUPATEN PONOROGO'),
            229 => array('id' => '3503', 'provinsi_id' => '35', 'kota' => 'KABUPATEN TRENGGALEK'),
            230 => array('id' => '3504', 'provinsi_id' => '35', 'kota' => 'KABUPATEN TULUNGAGUNG'),
            231 => array('id' => '3505', 'provinsi_id' => '35', 'kota' => 'KABUPATEN BLITAR'),
            232 => array('id' => '3506', 'provinsi_id' => '35', 'kota' => 'KABUPATEN KEDIRI'),
            233 => array('id' => '3507', 'provinsi_id' => '35', 'kota' => 'KABUPATEN MALANG'),
            234 => array('id' => '3508', 'provinsi_id' => '35', 'kota' => 'KABUPATEN LUMAJANG'),
            235 => array('id' => '3509', 'provinsi_id' => '35', 'kota' => 'KABUPATEN JEMBER'),
            236 => array('id' => '3510', 'provinsi_id' => '35', 'kota' => 'KABUPATEN BANYUWANGI'),
            237 => array('id' => '3511', 'provinsi_id' => '35', 'kota' => 'KABUPATEN BONDOWOSO'),
            238 => array('id' => '3512', 'provinsi_id' => '35', 'kota' => 'KABUPATEN SITUBONDO'),
            239 => array('id' => '3513', 'provinsi_id' => '35', 'kota' => 'KABUPATEN PROBOLINGGO'),
            240 => array('id' => '3514', 'provinsi_id' => '35', 'kota' => 'KABUPATEN PASURUAN'),
            241 => array('id' => '3515', 'provinsi_id' => '35', 'kota' => 'KABUPATEN SIDOARJO'),
            242 => array('id' => '3516', 'provinsi_id' => '35', 'kota' => 'KABUPATEN MOJOKERTO'),
            243 => array('id' => '3517', 'provinsi_id' => '35', 'kota' => 'KABUPATEN JOMBANG'),
            244 => array('id' => '3518', 'provinsi_id' => '35', 'kota' => 'KABUPATEN NGANJUK'),
            245 => array('id' => '3519', 'provinsi_id' => '35', 'kota' => 'KABUPATEN MADIUN'),
            246 => array('id' => '3520', 'provinsi_id' => '35', 'kota' => 'KABUPATEN MAGETAN'),
            247 => array('id' => '3521', 'provinsi_id' => '35', 'kota' => 'KABUPATEN NGAWI'),
            248 => array('id' => '3522', 'provinsi_id' => '35', 'kota' => 'KABUPATEN BOJONEGORO'),
            249 => array('id' => '3523', 'provinsi_id' => '35', 'kota' => 'KABUPATEN TUBAN'),
            250 => array('id' => '3524', 'provinsi_id' => '35', 'kota' => 'KABUPATEN LAMONGAN'),
            251 => array('id' => '3525', 'provinsi_id' => '35', 'kota' => 'KABUPATEN GRESIK'),
            252 => array('id' => '3526', 'provinsi_id' => '35', 'kota' => 'KABUPATEN BANGKALAN'),
            253 => array('id' => '3527', 'provinsi_id' => '35', 'kota' => 'KABUPATEN SAMPANG'),
            254 => array('id' => '3528', 'provinsi_id' => '35', 'kota' => 'KABUPATEN PAMEKASAN'),
            255 => array('id' => '3529', 'provinsi_id' => '35', 'kota' => 'KABUPATEN SUMENEP'),
            256 => array('id' => '3571', 'provinsi_id' => '35', 'kota' => 'KOTA KEDIRI'),
            257 => array('id' => '3572', 'provinsi_id' => '35', 'kota' => 'KOTA BLITAR'),
            258 => array('id' => '3573', 'provinsi_id' => '35', 'kota' => 'KOTA MALANG'),
            259 => array('id' => '3574', 'provinsi_id' => '35', 'kota' => 'KOTA PROBOLINGGO'),
            260 => array('id' => '3575', 'provinsi_id' => '35', 'kota' => 'KOTA PASURUAN'),
            261 => array('id' => '3576', 'provinsi_id' => '35', 'kota' => 'KOTA MOJOKERTO'),
            262 => array('id' => '3577', 'provinsi_id' => '35', 'kota' => 'KOTA MADIUN'),
            263 => array('id' => '3578', 'provinsi_id' => '35', 'kota' => 'KOTA SURABAYA'),
            264 => array('id' => '3579', 'provinsi_id' => '35', 'kota' => 'KOTA BATU'),
            265 => array('id' => '3601', 'provinsi_id' => '36', 'kota' => 'KABUPATEN PANDEGLANG'),
            266 => array('id' => '3602', 'provinsi_id' => '36', 'kota' => 'KABUPATEN LEBAK'),
            267 => array('id' => '3603', 'provinsi_id' => '36', 'kota' => 'KABUPATEN TANGERANG'),
            268 => array('id' => '3604', 'provinsi_id' => '36', 'kota' => 'KABUPATEN SERANG'),
            269 => array('id' => '3671', 'provinsi_id' => '36', 'kota' => 'KOTA TANGERANG'),
            270 => array('id' => '3672', 'provinsi_id' => '36', 'kota' => 'KOTA CILEGON'),
            271 => array('id' => '3673', 'provinsi_id' => '36', 'kota' => 'KOTA SERANG'),
            272 => array('id' => '3674', 'provinsi_id' => '36', 'kota' => 'KOTA TANGERANG SELATAN'),
            273 => array('id' => '5101', 'provinsi_id' => '51', 'kota' => 'KABUPATEN JEMBRANA'),
            274 => array('id' => '5102', 'provinsi_id' => '51', 'kota' => 'KABUPATEN TABANAN'),
            275 => array('id' => '5103', 'provinsi_id' => '51', 'kota' => 'KABUPATEN BADUNG'),
            276 => array('id' => '5104', 'provinsi_id' => '51', 'kota' => 'KABUPATEN GIANYAR'),
            277 => array('id' => '5105', 'provinsi_id' => '51', 'kota' => 'KABUPATEN KLUNGKUNG'),
            278 => array('id' => '5106', 'provinsi_id' => '51', 'kota' => 'KABUPATEN BANGLI'),
            279 => array('id' => '5107', 'provinsi_id' => '51', 'kota' => 'KABUPATEN KARANG ASEM'),
            280 => array('id' => '5108', 'provinsi_id' => '51', 'kota' => 'KABUPATEN BULELENG'),
            281 => array('id' => '5171', 'provinsi_id' => '51', 'kota' => 'KOTA DENPASAR'),
            282 => array('id' => '5201', 'provinsi_id' => '52', 'kota' => 'KABUPATEN LOMBOK BARAT'),
            283 => array('id' => '5202', 'provinsi_id' => '52', 'kota' => 'KABUPATEN LOMBOK TENGAH'),
            284 => array('id' => '5203', 'provinsi_id' => '52', 'kota' => 'KABUPATEN LOMBOK TIMUR'),
            285 => array('id' => '5204', 'provinsi_id' => '52', 'kota' => 'KABUPATEN SUMBAWA'),
            286 => array('id' => '5205', 'provinsi_id' => '52', 'kota' => 'KABUPATEN DOMPU'),
            287 => array('id' => '5206', 'provinsi_id' => '52', 'kota' => 'KABUPATEN BIMA'),
            288 => array('id' => '5207', 'provinsi_id' => '52', 'kota' => 'KABUPATEN SUMBAWA BARAT'),
            289 => array('id' => '5208', 'provinsi_id' => '52', 'kota' => 'KABUPATEN LOMBOK UTARA'),
            290 => array('id' => '5271', 'provinsi_id' => '52', 'kota' => 'KOTA MATARAM'),
            291 => array('id' => '5272', 'provinsi_id' => '52', 'kota' => 'KOTA BIMA'),
            292 => array('id' => '5301', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SUMBA BARAT'),
            293 => array('id' => '5302', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SUMBA TIMUR'),
            294 => array('id' => '5303', 'provinsi_id' => '53', 'kota' => 'KABUPATEN KUPANG'),
            295 => array('id' => '5304', 'provinsi_id' => '53', 'kota' => 'KABUPATEN TIMOR TENGAH SELATAN'),
            296 => array('id' => '5305', 'provinsi_id' => '53', 'kota' => 'KABUPATEN TIMOR TENGAH UTARA'),
            297 => array('id' => '5306', 'provinsi_id' => '53', 'kota' => 'KABUPATEN BELU'),
            298 => array('id' => '5307', 'provinsi_id' => '53', 'kota' => 'KABUPATEN ALOR'),
            299 => array('id' => '5308', 'provinsi_id' => '53', 'kota' => 'KABUPATEN LEMBATA'),
            300 => array('id' => '5309', 'provinsi_id' => '53', 'kota' => 'KABUPATEN FLORES TIMUR'),
            301 => array('id' => '5310', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SIKKA'),
            302 => array('id' => '5311', 'provinsi_id' => '53', 'kota' => 'KABUPATEN ENDE'),
            303 => array('id' => '5312', 'provinsi_id' => '53', 'kota' => 'KABUPATEN NGADA'),
            304 => array('id' => '5313', 'provinsi_id' => '53', 'kota' => 'KABUPATEN MANGGARAI'),
            305 => array('id' => '5314', 'provinsi_id' => '53', 'kota' => 'KABUPATEN ROTE NDAO'),
            306 => array('id' => '5315', 'provinsi_id' => '53', 'kota' => 'KABUPATEN MANGGARAI BARAT'),
            307 => array('id' => '5316', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SUMBA TENGAH'),
            308 => array('id' => '5317', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SUMBA BARAT DAYA'),
            309 => array('id' => '5318', 'provinsi_id' => '53', 'kota' => 'KABUPATEN NAGEKEO'),
            310 => array('id' => '5319', 'provinsi_id' => '53', 'kota' => 'KABUPATEN MANGGARAI TIMUR'),
            311 => array('id' => '5320', 'provinsi_id' => '53', 'kota' => 'KABUPATEN SABU RAIJUA'),
            312 => array('id' => '5321', 'provinsi_id' => '53', 'kota' => 'KABUPATEN MALAKA'),
            313 => array('id' => '5371', 'provinsi_id' => '53', 'kota' => 'KOTA KUPANG'),
            314 => array('id' => '6101', 'provinsi_id' => '61', 'kota' => 'KABUPATEN SAMBAS'),
            315 => array('id' => '6102', 'provinsi_id' => '61', 'kota' => 'KABUPATEN BENGKAYANG'),
            316 => array('id' => '6103', 'provinsi_id' => '61', 'kota' => 'KABUPATEN LANDAK'),
            317 => array('id' => '6104', 'provinsi_id' => '61', 'kota' => 'KABUPATEN MEMPAWAH'),
            318 => array('id' => '6105', 'provinsi_id' => '61', 'kota' => 'KABUPATEN SANGGAU'),
            319 => array('id' => '6106', 'provinsi_id' => '61', 'kota' => 'KABUPATEN KETAPANG'),
            320 => array('id' => '6107', 'provinsi_id' => '61', 'kota' => 'KABUPATEN SINTANG'),
            321 => array('id' => '6108', 'provinsi_id' => '61', 'kota' => 'KABUPATEN KAPUAS HULU'),
            322 => array('id' => '6109', 'provinsi_id' => '61', 'kota' => 'KABUPATEN SEKADAU'),
            323 => array('id' => '6110', 'provinsi_id' => '61', 'kota' => 'KABUPATEN MELAWI'),
            324 => array('id' => '6111', 'provinsi_id' => '61', 'kota' => 'KABUPATEN KAYONG UTARA'),
            325 => array('id' => '6112', 'provinsi_id' => '61', 'kota' => 'KABUPATEN KUBU RAYA'),
            326 => array('id' => '6171', 'provinsi_id' => '61', 'kota' => 'KOTA PONTIANAK'),
            327 => array('id' => '6172', 'provinsi_id' => '61', 'kota' => 'KOTA SINGKAWANG'),
            328 => array('id' => '6201', 'provinsi_id' => '62', 'kota' => 'KABUPATEN KOTAWARINGIN BARAT'),
            329 => array('id' => '6202', 'provinsi_id' => '62', 'kota' => 'KABUPATEN KOTAWARINGIN TIMUR'),
            330 => array('id' => '6203', 'provinsi_id' => '62', 'kota' => 'KABUPATEN KAPUAS'),
            331 => array('id' => '6204', 'provinsi_id' => '62', 'kota' => 'KABUPATEN BARITO SELATAN'),
            332 => array('id' => '6205', 'provinsi_id' => '62', 'kota' => 'KABUPATEN BARITO UTARA'),
            333 => array('id' => '6206', 'provinsi_id' => '62', 'kota' => 'KABUPATEN SUKAMARA'),
            334 => array('id' => '6207', 'provinsi_id' => '62', 'kota' => 'KABUPATEN LAMANDAU'),
            335 => array('id' => '6208', 'provinsi_id' => '62', 'kota' => 'KABUPATEN SERUYAN'),
            336 => array('id' => '6209', 'provinsi_id' => '62', 'kota' => 'KABUPATEN KATINGAN'),
            337 => array('id' => '6210', 'provinsi_id' => '62', 'kota' => 'KABUPATEN PULANG PISAU'),
            338 => array('id' => '6211', 'provinsi_id' => '62', 'kota' => 'KABUPATEN GUNUNG MAS'),
            339 => array('id' => '6212', 'provinsi_id' => '62', 'kota' => 'KABUPATEN BARITO TIMUR'),
            340 => array('id' => '6213', 'provinsi_id' => '62', 'kota' => 'KABUPATEN MURUNG RAYA'),
            341 => array('id' => '6271', 'provinsi_id' => '62', 'kota' => 'KOTA PALANGKA RAYA'),
            342 => array('id' => '6301', 'provinsi_id' => '63', 'kota' => 'KABUPATEN TANAH LAUT'),
            343 => array('id' => '6302', 'provinsi_id' => '63', 'kota' => 'KABUPATEN KOTA BARU'),
            344 => array('id' => '6303', 'provinsi_id' => '63', 'kota' => 'KABUPATEN BANJAR'),
            345 => array('id' => '6304', 'provinsi_id' => '63', 'kota' => 'KABUPATEN BARITO KUALA'),
            346 => array('id' => '6305', 'provinsi_id' => '63', 'kota' => 'KABUPATEN TAPIN'),
            347 => array('id' => '6306', 'provinsi_id' => '63', 'kota' => 'KABUPATEN HULU SUNGAI SELATAN'),
            348 => array('id' => '6307', 'provinsi_id' => '63', 'kota' => 'KABUPATEN HULU SUNGAI TENGAH'),
            349 => array('id' => '6308', 'provinsi_id' => '63', 'kota' => 'KABUPATEN HULU SUNGAI UTARA'),
            350 => array('id' => '6309', 'provinsi_id' => '63', 'kota' => 'KABUPATEN TABALONG'),
            351 => array('id' => '6310', 'provinsi_id' => '63', 'kota' => 'KABUPATEN TANAH BUMBU'),
            352 => array('id' => '6311', 'provinsi_id' => '63', 'kota' => 'KABUPATEN BALANGAN'),
            353 => array('id' => '6371', 'provinsi_id' => '63', 'kota' => 'KOTA BANJARMASIN'),
            354 => array('id' => '6372', 'provinsi_id' => '63', 'kota' => 'KOTA BANJAR BARU'),
            355 => array('id' => '6401', 'provinsi_id' => '64', 'kota' => 'KABUPATEN PASER'),
            356 => array('id' => '6402', 'provinsi_id' => '64', 'kota' => 'KABUPATEN KUTAI BARAT'),
            357 => array('id' => '6403', 'provinsi_id' => '64', 'kota' => 'KABUPATEN KUTAI KARTANEGARA'),
            358 => array('id' => '6404', 'provinsi_id' => '64', 'kota' => 'KABUPATEN KUTAI TIMUR'),
            359 => array('id' => '6405', 'provinsi_id' => '64', 'kota' => 'KABUPATEN BERAU'),
            360 => array('id' => '6409', 'provinsi_id' => '64', 'kota' => 'KABUPATEN PENAJAM PASER UTARA'),
            361 => array('id' => '6411', 'provinsi_id' => '64', 'kota' => 'KABUPATEN MAHAKAM HULU'),
            362 => array('id' => '6471', 'provinsi_id' => '64', 'kota' => 'KOTA BALIKPAPAN'),
            363 => array('id' => '6472', 'provinsi_id' => '64', 'kota' => 'KOTA SAMARINDA'),
            364 => array('id' => '6474', 'provinsi_id' => '64', 'kota' => 'KOTA BONTANG'),
            365 => array('id' => '6501', 'provinsi_id' => '65', 'kota' => 'KABUPATEN MALINAU'),
            366 => array('id' => '6502', 'provinsi_id' => '65', 'kota' => 'KABUPATEN BULUNGAN'),
            367 => array('id' => '6503', 'provinsi_id' => '65', 'kota' => 'KABUPATEN TANA TIDUNG'),
            368 => array('id' => '6504', 'provinsi_id' => '65', 'kota' => 'KABUPATEN NUNUKAN'),
            369 => array('id' => '6571', 'provinsi_id' => '65', 'kota' => 'KOTA TARAKAN'),
            370 => array('id' => '7101', 'provinsi_id' => '71', 'kota' => 'KABUPATEN BOLAANG MONGONDOW'),
            371 => array('id' => '7102', 'provinsi_id' => '71', 'kota' => 'KABUPATEN MINAHASA'),
            372 => array('id' => '7103', 'provinsi_id' => '71', 'kota' => 'KABUPATEN KEPULAUAN SANGIHE'),
            373 => array('id' => '7104', 'provinsi_id' => '71', 'kota' => 'KABUPATEN KEPULAUAN TALAUD'),
            374 => array('id' => '7105', 'provinsi_id' => '71', 'kota' => 'KABUPATEN MINAHASA SELATAN'),
            375 => array('id' => '7106', 'provinsi_id' => '71', 'kota' => 'KABUPATEN MINAHASA UTARA'),
            376 => array('id' => '7107', 'provinsi_id' => '71', 'kota' => 'KABUPATEN BOLAANG MONGONDOW UTARA'),
            377 => array('id' => '7108', 'provinsi_id' => '71', 'kota' => 'KABUPATEN SIAU TAGULANDANG BIARO'),
            378 => array('id' => '7109', 'provinsi_id' => '71', 'kota' => 'KABUPATEN MINAHASA TENGGARA'),
            379 => array('id' => '7110', 'provinsi_id' => '71', 'kota' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'),
            380 => array('id' => '7111', 'provinsi_id' => '71', 'kota' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'),
            381 => array('id' => '7171', 'provinsi_id' => '71', 'kota' => 'KOTA MANADO'),
            382 => array('id' => '7172', 'provinsi_id' => '71', 'kota' => 'KOTA BITUNG'),
            383 => array('id' => '7173', 'provinsi_id' => '71', 'kota' => 'KOTA TOMOHON'),
            384 => array('id' => '7174', 'provinsi_id' => '71', 'kota' => 'KOTA KOTAMOBAGU'),
            385 => array('id' => '7201', 'provinsi_id' => '72', 'kota' => 'KABUPATEN BANGGAI KEPULAUAN'),
            386 => array('id' => '7202', 'provinsi_id' => '72', 'kota' => 'KABUPATEN BANGGAI'),
            387 => array('id' => '7203', 'provinsi_id' => '72', 'kota' => 'KABUPATEN MOROWALI'),
            388 => array('id' => '7204', 'provinsi_id' => '72', 'kota' => 'KABUPATEN POSO'),
            389 => array('id' => '7205', 'provinsi_id' => '72', 'kota' => 'KABUPATEN DONGGALA'),
            390 => array('id' => '7206', 'provinsi_id' => '72', 'kota' => 'KABUPATEN TOLI-TOLI'),
            391 => array('id' => '7207', 'provinsi_id' => '72', 'kota' => 'KABUPATEN BUOL'),
            392 => array('id' => '7208', 'provinsi_id' => '72', 'kota' => 'KABUPATEN PARIGI MOUTONG'),
            393 => array('id' => '7209', 'provinsi_id' => '72', 'kota' => 'KABUPATEN TOJO UNA-UNA'),
            394 => array('id' => '7210', 'provinsi_id' => '72', 'kota' => 'KABUPATEN SIGI'),
            395 => array('id' => '7211', 'provinsi_id' => '72', 'kota' => 'KABUPATEN BANGGAI LAUT'),
            396 => array('id' => '7212', 'provinsi_id' => '72', 'kota' => 'KABUPATEN MOROWALI UTARA'),
            397 => array('id' => '7271', 'provinsi_id' => '72', 'kota' => 'KOTA PALU'),
            398 => array('id' => '7301', 'provinsi_id' => '73', 'kota' => 'KABUPATEN KEPULAUAN SELAYAR'),
            399 => array('id' => '7302', 'provinsi_id' => '73', 'kota' => 'KABUPATEN BULUKUMBA'),
            400 => array('id' => '7303', 'provinsi_id' => '73', 'kota' => 'KABUPATEN BANTAENG'),
            401 => array('id' => '7304', 'provinsi_id' => '73', 'kota' => 'KABUPATEN JENEPONTO'),
            402 => array('id' => '7305', 'provinsi_id' => '73', 'kota' => 'KABUPATEN TAKALAR'),
            403 => array('id' => '7306', 'provinsi_id' => '73', 'kota' => 'KABUPATEN GOWA'),
            404 => array('id' => '7307', 'provinsi_id' => '73', 'kota' => 'KABUPATEN SINJAI'),
            405 => array('id' => '7308', 'provinsi_id' => '73', 'kota' => 'KABUPATEN MAROS'),
            406 => array('id' => '7309', 'provinsi_id' => '73', 'kota' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'),
            407 => array('id' => '7310', 'provinsi_id' => '73', 'kota' => 'KABUPATEN BARRU'),
            408 => array('id' => '7311', 'provinsi_id' => '73', 'kota' => 'KABUPATEN BONE'),
            409 => array('id' => '7312', 'provinsi_id' => '73', 'kota' => 'KABUPATEN SOPPENG'),
            410 => array('id' => '7313', 'provinsi_id' => '73', 'kota' => 'KABUPATEN WAJO'),
            411 => array('id' => '7314', 'provinsi_id' => '73', 'kota' => 'KABUPATEN SIDENRENG RAPPANG'),
            412 => array('id' => '7315', 'provinsi_id' => '73', 'kota' => 'KABUPATEN PINRANG'),
            413 => array('id' => '7316', 'provinsi_id' => '73', 'kota' => 'KABUPATEN ENREKANG'),
            414 => array('id' => '7317', 'provinsi_id' => '73', 'kota' => 'KABUPATEN LUWU'),
            415 => array('id' => '7318', 'provinsi_id' => '73', 'kota' => 'KABUPATEN TANA TORAJA'),
            416 => array('id' => '7322', 'provinsi_id' => '73', 'kota' => 'KABUPATEN LUWU UTARA'),
            417 => array('id' => '7325', 'provinsi_id' => '73', 'kota' => 'KABUPATEN LUWU TIMUR'),
            418 => array('id' => '7326', 'provinsi_id' => '73', 'kota' => 'KABUPATEN TORAJA UTARA'),
            419 => array('id' => '7371', 'provinsi_id' => '73', 'kota' => 'KOTA MAKASSAR'),
            420 => array('id' => '7372', 'provinsi_id' => '73', 'kota' => 'KOTA PAREPARE'),
            421 => array('id' => '7373', 'provinsi_id' => '73', 'kota' => 'KOTA PALOPO'),
            422 => array('id' => '7401', 'provinsi_id' => '74', 'kota' => 'KABUPATEN BUTON'),
            423 => array('id' => '7402', 'provinsi_id' => '74', 'kota' => 'KABUPATEN MUNA'),
            424 => array('id' => '7403', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KONAWE'),
            425 => array('id' => '7404', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KOLAKA'),
            426 => array('id' => '7405', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KONAWE SELATAN'),
            427 => array('id' => '7406', 'provinsi_id' => '74', 'kota' => 'KABUPATEN BOMBANA'),
            428 => array('id' => '7407', 'provinsi_id' => '74', 'kota' => 'KABUPATEN WAKATOBI'),
            429 => array('id' => '7408', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KOLAKA UTARA'),
            430 => array('id' => '7409', 'provinsi_id' => '74', 'kota' => 'KABUPATEN BUTON UTARA'),
            431 => array('id' => '7410', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KONAWE UTARA'),
            432 => array('id' => '7411', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KOLAKA TIMUR'),
            433 => array('id' => '7412', 'provinsi_id' => '74', 'kota' => 'KABUPATEN KONAWE KEPULAUAN'),
            434 => array('id' => '7413', 'provinsi_id' => '74', 'kota' => 'KABUPATEN MUNA BARAT'),
            435 => array('id' => '7414', 'provinsi_id' => '74', 'kota' => 'KABUPATEN BUTON TENGAH'),
            436 => array('id' => '7415', 'provinsi_id' => '74', 'kota' => 'KABUPATEN BUTON SELATAN'),
            437 => array('id' => '7471', 'provinsi_id' => '74', 'kota' => 'KOTA KENDARI'),
            438 => array('id' => '7472', 'provinsi_id' => '74', 'kota' => 'KOTA BAUBAU'),
            439 => array('id' => '7501', 'provinsi_id' => '75', 'kota' => 'KABUPATEN BOALEMO'),
            440 => array('id' => '7502', 'provinsi_id' => '75', 'kota' => 'KABUPATEN GORONTALO'),
            441 => array('id' => '7503', 'provinsi_id' => '75', 'kota' => 'KABUPATEN POHUWATO'),
            442 => array('id' => '7504', 'provinsi_id' => '75', 'kota' => 'KABUPATEN BONE BOLANGO'),
            443 => array('id' => '7505', 'provinsi_id' => '75', 'kota' => 'KABUPATEN GORONTALO UTARA'),
            444 => array('id' => '7571', 'provinsi_id' => '75', 'kota' => 'KOTA GORONTALO'),
            445 => array('id' => '7601', 'provinsi_id' => '76', 'kota' => 'KABUPATEN MAJENE'),
            446 => array('id' => '7602', 'provinsi_id' => '76', 'kota' => 'KABUPATEN POLEWALI MANDAR'),
            447 => array('id' => '7603', 'provinsi_id' => '76', 'kota' => 'KABUPATEN MAMASA'),
            448 => array('id' => '7604', 'provinsi_id' => '76', 'kota' => 'KABUPATEN MAMUJU'),
            449 => array('id' => '7605', 'provinsi_id' => '76', 'kota' => 'KABUPATEN MAMUJU UTARA'),
            450 => array('id' => '7606', 'provinsi_id' => '76', 'kota' => 'KABUPATEN MAMUJU TENGAH'),
            451 => array('id' => '8101', 'provinsi_id' => '81', 'kota' => 'KABUPATEN MALUKU TENGGARA BARAT'),
            452 => array('id' => '8102', 'provinsi_id' => '81', 'kota' => 'KABUPATEN MALUKU TENGGARA'),
            453 => array('id' => '8103', 'provinsi_id' => '81', 'kota' => 'KABUPATEN MALUKU TENGAH'),
            454 => array('id' => '8104', 'provinsi_id' => '81', 'kota' => 'KABUPATEN BURU'),
            455 => array('id' => '8105', 'provinsi_id' => '81', 'kota' => 'KABUPATEN KEPULAUAN ARU'),
            456 => array('id' => '8106', 'provinsi_id' => '81', 'kota' => 'KABUPATEN SERAM BAGIAN BARAT'),
            457 => array('id' => '8107', 'provinsi_id' => '81', 'kota' => 'KABUPATEN SERAM BAGIAN TIMUR'),
            458 => array('id' => '8108', 'provinsi_id' => '81', 'kota' => 'KABUPATEN MALUKU BARAT DAYA'),
            459 => array('id' => '8109', 'provinsi_id' => '81', 'kota' => 'KABUPATEN BURU SELATAN'),
            460 => array('id' => '8171', 'provinsi_id' => '81', 'kota' => 'KOTA AMBON'),
            461 => array('id' => '8172', 'provinsi_id' => '81', 'kota' => 'KOTA TUAL'),
            462 => array('id' => '8201', 'provinsi_id' => '82', 'kota' => 'KABUPATEN HALMAHERA BARAT'),
            463 => array('id' => '8202', 'provinsi_id' => '82', 'kota' => 'KABUPATEN HALMAHERA TENGAH'),
            464 => array('id' => '8203', 'provinsi_id' => '82', 'kota' => 'KABUPATEN KEPULAUAN SULA'),
            465 => array('id' => '8204', 'provinsi_id' => '82', 'kota' => 'KABUPATEN HALMAHERA SELATAN'),
            466 => array('id' => '8205', 'provinsi_id' => '82', 'kota' => 'KABUPATEN HALMAHERA UTARA'),
            467 => array('id' => '8206', 'provinsi_id' => '82', 'kota' => 'KABUPATEN HALMAHERA TIMUR'),
            468 => array('id' => '8207', 'provinsi_id' => '82', 'kota' => 'KABUPATEN PULAU MOROTAI'),
            469 => array('id' => '8208', 'provinsi_id' => '82', 'kota' => 'KABUPATEN PULAU TALIABU'),
            470 => array('id' => '8271', 'provinsi_id' => '82', 'kota' => 'KOTA TERNATE'),
            471 => array('id' => '8272', 'provinsi_id' => '82', 'kota' => 'KOTA TIDORE KEPULAUAN'),
            472 => array('id' => '9101', 'provinsi_id' => '91', 'kota' => 'KABUPATEN FAKFAK'),
            473 => array('id' => '9102', 'provinsi_id' => '91', 'kota' => 'KABUPATEN KAIMANA'),
            474 => array('id' => '9103', 'provinsi_id' => '91', 'kota' => 'KABUPATEN TELUK WONDAMA'),
            475 => array('id' => '9104', 'provinsi_id' => '91', 'kota' => 'KABUPATEN TELUK BINTUNI'),
            476 => array('id' => '9105', 'provinsi_id' => '91', 'kota' => 'KABUPATEN MANOKWARI'),
            477 => array('id' => '9106', 'provinsi_id' => '91', 'kota' => 'KABUPATEN SORONG SELATAN'),
            478 => array('id' => '9107', 'provinsi_id' => '91', 'kota' => 'KABUPATEN SORONG'),
            479 => array('id' => '9108', 'provinsi_id' => '91', 'kota' => 'KABUPATEN RAJA AMPAT'),
            480 => array('id' => '9109', 'provinsi_id' => '91', 'kota' => 'KABUPATEN TAMBRAUW'),
            481 => array('id' => '9110', 'provinsi_id' => '91', 'kota' => 'KABUPATEN MAYBRAT'),
            482 => array('id' => '9111', 'provinsi_id' => '91', 'kota' => 'KABUPATEN MANOKWARI SELATAN'),
            483 => array('id' => '9112', 'provinsi_id' => '91', 'kota' => 'KABUPATEN PEGUNUNGAN ARFAK'),
            484 => array('id' => '9171', 'provinsi_id' => '91', 'kota' => 'KOTA SORONG'),
            485 => array('id' => '9401', 'provinsi_id' => '94', 'kota' => 'KABUPATEN MERAUKE'),
            486 => array('id' => '9402', 'provinsi_id' => '94', 'kota' => 'KABUPATEN JAYAWIJAYA'),
            487 => array('id' => '9403', 'provinsi_id' => '94', 'kota' => 'KABUPATEN JAYAPURA'),
            488 => array('id' => '9404', 'provinsi_id' => '94', 'kota' => 'KABUPATEN NABIRE'),
            489 => array('id' => '9408', 'provinsi_id' => '94', 'kota' => 'KABUPATEN KEPULAUAN YAPEN'),
            490 => array('id' => '9409', 'provinsi_id' => '94', 'kota' => 'KABUPATEN BIAK NUMFOR'),
            491 => array('id' => '9410', 'provinsi_id' => '94', 'kota' => 'KABUPATEN PANIAI'),
            492 => array('id' => '9411', 'provinsi_id' => '94', 'kota' => 'KABUPATEN PUNCAK JAYA'),
            493 => array('id' => '9412', 'provinsi_id' => '94', 'kota' => 'KABUPATEN MIMIKA'),
            494 => array('id' => '9413', 'provinsi_id' => '94', 'kota' => 'KABUPATEN BOVEN DIGOEL'),
            495 => array('id' => '9414', 'provinsi_id' => '94', 'kota' => 'KABUPATEN MAPPI'),
            496 => array('id' => '9415', 'provinsi_id' => '94', 'kota' => 'KABUPATEN ASMAT'),
            497 => array('id' => '9416', 'provinsi_id' => '94', 'kota' => 'KABUPATEN YAHUKIMO'),
            498 => array('id' => '9417', 'provinsi_id' => '94', 'kota' => 'KABUPATEN PEGUNUNGAN BINTANG'),
            499 => array('id' => '9418', 'provinsi_id' => '94', 'kota' => 'KABUPATEN TOLIKARA'),
            500 => array('id' => '9419', 'provinsi_id' => '94', 'kota' => 'KABUPATEN SARMI'),
            501 => array('id' => '9420', 'provinsi_id' => '94', 'kota' => 'KABUPATEN KEEROM'),
            502 => array('id' => '9426', 'provinsi_id' => '94', 'kota' => 'KABUPATEN WAROPEN'),
            503 => array('id' => '9427', 'provinsi_id' => '94', 'kota' => 'KABUPATEN SUPIORI'),
            504 => array('id' => '9428', 'provinsi_id' => '94', 'kota' => 'KABUPATEN MAMBERAMO RAYA'),
            505 => array('id' => '9429', 'provinsi_id' => '94', 'kota' => 'KABUPATEN NDUGA'),
            506 => array('id' => '9430', 'provinsi_id' => '94', 'kota' => 'KABUPATEN LANNY JAYA'),
            507 => array('id' => '9431', 'provinsi_id' => '94', 'kota' => 'KABUPATEN MAMBERAMO TENGAH'),
            508 => array('id' => '9432', 'provinsi_id' => '94', 'kota' => 'KABUPATEN YALIMO'),
            509 => array('id' => '9433', 'provinsi_id' => '94', 'kota' => 'KABUPATEN PUNCAK'),
            510 => array('id' => '9434', 'provinsi_id' => '94', 'kota' => 'KABUPATEN DOGIYAI'),
            511 => array('id' => '9435', 'provinsi_id' => '94', 'kota' => 'KABUPATEN INTAN JAYA'),
            512 => array('id' => '9436', 'provinsi_id' => '94', 'kota' => 'KABUPATEN DEIYAI'),
            513 => array('id' => '9471', 'provinsi_id' => '94', 'kota' => 'KOTA JAYAPURA'),
        );

        $insert = DB::table('kota')->insert($kota);
    }
}
